### ISSUE TITLE
Cannot evaluate unlinearized (JSON) version of value(project_name) call

### ISSUE THREAD

**Issue by lucaswerkmeister** [google/abstracttext#12]
The next implementation step for [GraalEneyj](https://github.com/lucaswerkmeister/graaleneyj/) is probably to implement function calls, and I figured that `value(project_name)` seems like a good first call to target: it uses a builtin (so no need to implement custom functions yet) and should be relatively simple overall. GraalEneyj also doesn’t support anything other than the canonical JSON representation yet, so I needed the JSON version of a function call. Eneyj can print that, fortunately:

```console
> .evaluation off
evaluation is off

> .linearization off
linearization is off

> value(project_name)
{
  "Z1K1": "Z7",
  "Z7K1": "Z36",
  "K1": "Z28"
}
```

However, it looks like Eneyj is itself unable to evaluate that function call:

```console
> {"Z1K1": "Z7", "Z7K1": "Z36", "K1": "Z28"}
error_in_function:
by_key(error(error_in_function, error(zobject_has_no_type, "Z36", "val"), nothing), "Z5K2")
```

So far, I was under the impression that the Eneyj CLI also accepted the canonical JSON representation, so this should work. Am I doing something wrong, or is this a bug in Eneyj?

**Comment by vrandezo** [comment]
Bug in eneyj, it doesn't make sense it doesn't work. I never implemented that, good catch.

This one works:

`{"Z1K1": "Z7", "Z7K1": {"Z1K1": "Z9", "Z9K1": "Z36"}, "K1": {"Z1K1": "Z9", "Z9K1": "Z28"}}`

So really it should extend the code first, then it would work. Thanks for the bug report!

**Comment by lucaswerkmeister** [comment]
Alright, thanks!

**Comment by vrandezo** [comment]
The commit should fix that. Let me know if it works, then we can close this.

**Comment by lucaswerkmeister** [comment]
Thanks, it seems to be working now!
